//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#include <Core.h>

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_mscorlib;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Native;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Stm32;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Devices_Can;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Graphics;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Devices_OneWire;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_ResourceManager;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_System_Collections;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_System_Text;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Events;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Runtime_Events_EventSink_DriverProcs;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_IO_FileSystem;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Math;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Adc;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Device_Dac;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Device_Gpio;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Gpio;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_I2c;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Device_I2c;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Pwm;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_SerialCommunication;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_IO_Ports;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Devices_Spi;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_System_Device_Spi;
extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Windows_Storage;

const CLR_RT_NativeAssemblyData *g_CLR_InteropAssembliesNativeData[] =
    {
        &g_CLR_AssemblyNative_mscorlib,
        &g_CLR_AssemblyNative_nanoFramework_Runtime_Native,
        &g_CLR_AssemblyNative_nanoFramework_Hardware_Stm32,
        &g_CLR_AssemblyNative_nanoFramework_Devices_Can,
        &g_CLR_AssemblyNative_nanoFramework_Graphics,
        &g_CLR_AssemblyNative_nanoFramework_Devices_OneWire,
        &g_CLR_AssemblyNative_nanoFramework_ResourceManager,
        &g_CLR_AssemblyNative_nanoFramework_System_Collections,
        &g_CLR_AssemblyNative_nanoFramework_System_Text,
        &g_CLR_AssemblyNative_nanoFramework_Runtime_Events,
        &g_CLR_AssemblyNative_nanoFramework_Runtime_Events_EventSink_DriverProcs,
        &g_CLR_AssemblyNative_System_IO_FileSystem,
        &g_CLR_AssemblyNative_System_Math,
        &g_CLR_AssemblyNative_Windows_Devices_Adc,
        &g_CLR_AssemblyNative_System_Device_Dac,
        &g_CLR_AssemblyNative_System_Device_Gpio,
        &g_CLR_AssemblyNative_Windows_Devices_Gpio,
        &g_CLR_AssemblyNative_Windows_Devices_I2c,
        &g_CLR_AssemblyNative_System_Device_I2c,
        &g_CLR_AssemblyNative_Windows_Devices_Pwm,
        &g_CLR_AssemblyNative_Windows_Devices_SerialCommunication,
        &g_CLR_AssemblyNative_System_IO_Ports,
        &g_CLR_AssemblyNative_Windows_Devices_Spi,
        &g_CLR_AssemblyNative_System_Device_Spi,
        &g_CLR_AssemblyNative_Windows_Storage,
        NULL};

uint16_t g_CLR_InteropAssembliesCount = (23 + 2);
