//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#ifndef _TARGET_PLATFORM_H_
#define _TARGET_PLATFORM_H_

#define NF_FEATURE_USE_SPIFFS FALSE
#define HAL_USE_RTC TRUE

// takes care of enabling the HAL subsystems required for API options
#define HAL_USE_SPI FALSE
#define HAL_USE_I2C TRUE
#define HAL_USE_PWM TRUE
#define HAL_USE_ADC FALSE
#define HAL_USE_DAC FALSE
#define HAL_USE_UART TRUE
#define HAL_USE_MAC FALSE
#define HAL_USE_SDC FALSE
#define HAL_USE_WDG TRUE
#define HAL_USE_CAN FALSE
#define HAL_NF_USE_STM32_CRC TRUE
#define HAL_NF_USE_STM32_ONEWIRE FALSE
#define HAL_USBH_USE_MSD FALSE

#endif /* _TARGET_PLATFORM_H_ */
