@startuml
ditaa
+--------+
|        |
|  Text  |
|Document|   
|        |   
+---+----+
|        |
|  Text  |
|Document|   
|        |   
+---+----+
|        |
|  Text  |
|Document|   
|        |   
+---+----+
@enduml
