//
// Copyright (c) .NET Foundation and Contributors
// See LICENSE file in the project root for full license information.
//

//////////////////////////////////////////////////////////////////////////////
// This file was automatically generated by a tool.                         //
// Any changes you make here will be overwritten when it's generated again. //
//////////////////////////////////////////////////////////////////////////////

#ifndef _TARGET_BOARD_NANOBOOTER_H_
#define _TARGET_BOARD_NANOBOOTER_H_

#include <target_common.h>

#define OEMSYSTEMINFOSTRING "nanoCLR running STM32H735G-DK"
#define NANOCLR_GRAPHICS TRUE
#define NANOCLR_GRAPHICS_USING_SPI FALSE

#endif /* _TARGET_BOARD_NANOBOOTER_H_ */
